name: Build & Deploy Patient Service

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy patient service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Verify Files Exist
        run: ls -R patient-service || exit 1

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Run Unit Tests
        run: |
          cd patient-service
          mvn -B test

      - name: Build Application
        run: |
          cd patient-service
          mvn clean package

      - name: Purge Docker Cache (if needed)
        run: docker builder prune --all --force || true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./patient-service
          file: ./patient-service/Dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/patient-service:today

      - name: Run the container
        run: |
          docker run -d -p 4000:4000 --name patient-service ${{ secrets.DOCKER_HUB_USERNAME }}/patient-service:today