name: Build & Deploy Patient Service

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy patient service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Verify POM file
        run: ls -l patient-service/pom.xml || exit 1

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Unit Tests
        run: |
          cd patient-service
          mvn -B test

      - name: Build the application
        run: |
          cd patient-service
          mvn clean
          mvn -B package

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: patient-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/patient-service:today