name: Build & Deploy Patient Service

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Patient Service
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK 21 for Maven build
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 4: Install dependencies and run unit tests (specify pom.xml location)
      - name: Unit Tests
        run: mvn -B test --file ./patient-service/pom.xml

      # Step 5: Build the application (specify pom.xml location)
      - name: Build the application
        run: |
          mvn clean --file ./patient-service/pom.xml
          mvn -B package --file ./patient-service/pom.xml

      # Step 6: Build Docker Image for Patient Service
      - name: Build Docker Image for Patient Service
        run: |
          docker-compose -f patient-service/docker-compose.yml build

      # Step 7: Run Docker Compose to Start Containers (PostgreSQL and Patient Service)
      - name: Run Docker Compose
        run: |
          docker-compose -f patient-service/docker-compose.yml up -d

      # Step 8: Wait for PostgreSQL container to be ready
      - name: Wait for PostgreSQL
        run: |
          until docker exec patient-service-db pg_isready -U admin_user -d db; do
            echo "Waiting for database to be ready..."
            sleep 5
          done

      - name: Verify Running Containers
        run: docker ps -a

      # Step 9: Run Post-Deployment Tasks
      - name: Run Post-Deployment Tasks
        run: |
          echo "Waiting for Patient Service to be ready..."

      # Step 10: Push Docker Image to Docker Hub (optional if you want to push to a registry)
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/patient-service:today ./patient-service
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/patient-service:today
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/patient-service-db:today ./patient-service
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/patient-service-db:today